// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpplpmjlhgbijzaexcqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcGxwbWpsaGdiaWp6YWV4Y3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDc3MjgsImV4cCI6MjA2NDA4MzcyOH0.okLCwJqhfwW19_CtXUDM3__RiTvn3J2bmzNj9QY97bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);